platform: linux-amd64
conda:
  channels:
    - conda-forge
dependencies:
  - python=3.9.6
  - robocorp-browser==1.0.2
  - robocorp-excel==0.4.0
  - robocorp-http==0.2.0
  - rpaframework==23.5.2
  - selenium
  - openpyxl
  - requests
  - google-chrome-stable    
  - chromedriver            
